### ISSUE TITLE
compose is not configured correctly

### ISSUE THREAD

**Issue by aviadhahami** [PlaytikaOSS/Leaktopus#1]
👋 
I'm trying to run this but the compose dies of various reasons each time; here's a kibana throw example:
```sh
[2022-07-03T09:20:08.469+00:00][FATAL][root] Error: [config validation of [xpack.security].enabled]: definition for this key is missing
```

Do you mind sharing your full setup?

**Comment by rotemplay** [comment]
@aviadhahami - I've updated the README with a missing step of creating a local .env file.
Please take a look and let me know if it solves your problem.
https://github.com/Playtika/Leaktopus#installation

**Comment by DanielAzulayy** [comment]
@aviadhahami Make sure you add your own GITHUB_ACCESS_TOKEN, and remove the [] in the .env file.

**Comment by aviadhahami** [comment]
Works now (compose-wise), but im getting 403s from GH?
![image](https://user-images.githubusercontent.com/7353632/177385659-f38d81ba-c37d-4ea2-961f-d4d7915d1319.png)

**Comment by rotemplay** [comment]
Thanks @DanielAzulayy . I've clarified that in the documentation, see #2  .
@aviadhahami - that's fine, it has an automatic retry mechanism and it will try again every 10 seconds until it'll be completed.
